security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      id: App\Security\CustomUserProvider
      # entity:
      #     class: App\Entity\User
      #     property: email

  role_hierarchy:
    class: App\Security\CustomRoleHierarchy
    arguments:
      - "@doctrine.orm.entity_manager"
    ROLE_DEV: [ROLE_MANAGER]

  firewalls:
    api_v1_auth:
      pattern: ^/api/v1/auth
      security: false
    api_v1:
      pattern: ^/api/v1
      stateless: true
      custom_authenticator: App\Security\JWTAuthenticator
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
        target: index

  access_control:
    - { path: ^/api/v1/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/roles$, roles: ROLE_DEV }
    - { path: ^/users$, roles: ROLE_MANAGER }
    - { path: ^/?$, roles: ROLE_USER }
